# Generated by Django 3.1.7 on 2021-11-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation_management_tool', '0003_auto_20211105_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='language',
            new_name='languagees',
        ),
    ]
