# Generated by Django 3.1.7 on 2021-11-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_management_tool', '0005_auto_20211105_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='languages',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
