# Generated by Django 3.1.7 on 2021-11-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_management_tool', '0008_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='x',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
