# Generated by Django 3.1.7 on 2021-11-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_management_tool', '0009_translation_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='x',
        ),
        migrations.AddField(
            model_name='translation',
            name='1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(to='translation_management_tool.Language'),
        ),
    ]
