# Generated by Django 3.1.7 on 2021-11-09 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation_management_tool', '0010_auto_20211109_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='translation_management_tool.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('project', 'language', 'key')},
        ),
        migrations.RemoveField(
            model_name='translation',
            name='1',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='2',
        ),
    ]
