# Generated by Django 3.1.7 on 2021-11-09 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation_management_tool', '0011_auto_20211109_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['code']},
        ),
        migrations.RenameField(
            model_name='language',
            old_name='languages',
            new_name='code',
        ),
    ]
