# Generated by Django 3.2.9 on 2021-11-09 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation_management_tool', '0012_auto_20211109_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation_management_tool.project')),
            ],
            options={
                'verbose_name': 'Translationkey',
                'verbose_name_plural': 'Translationkeys',
                'unique_together': {('project', 'key')},
            },
        ),
        migrations.AlterField(
            model_name='translation',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation_management_tool.translationkey'),
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('language', 'key')},
        ),
        migrations.RemoveField(
            model_name='translation',
            name='project',
        ),
    ]
