# Generated by Django 3.2.9 on 2021-11-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation_management_tool', '0013_auto_20211109_1717'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('language', 'value')},
        ),
    ]
