# Generated by Django 3.2.9 on 2021-11-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_management_tool', '0014_alter_translation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='value',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='translationkey',
            name='key',
            field=models.CharField(help_text="<b>Do not use the following endings in key: </b><br> $t(KEY_NAME) replace KEY_NAME with a  different translation key to use it in this translation</p><p><b>Interpolate: </b><br> {{VALUE}} replace VALUE with a variable that is defined for this translation.</p> <p>For more information about the i18next value standart <a href='https://www.i18next.com/misc/json-format' target='_blank'>click here</a>.</p>", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('language', 'key')},
        ),
    ]
