# Generated by Django 3.2.9 on 2021-12-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation_management_tool', '0018_alter_translationkey_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translationkey',
            unique_together={('project', 'key', 'depth')},
        ),
    ]
