# Generated by Django 3.2.9 on 2022-01-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation_management_tool', '0020_customimport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomImport',
        ),
    ]
