# Generated by Django 3.2.9 on 2022-01-11 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation_management_tool', '0021_delete_customimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('current_datetime', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation_management_tool.language')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation_management_tool.project')),
            ],
            options={
                'verbose_name': 'JSON Import',
                'verbose_name_plural': 'Imports',
                'unique_together': {('language', 'project', 'current_datetime')},
            },
        ),
    ]
