# Generated by Django 3.2.9 on 2022-01-11 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('translation_management_tool', '0022_jsonimport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jsonimport',
            options={'verbose_name': 'JSON Import', 'verbose_name_plural': 'JSON Imports'},
        ),
        migrations.AddField(
            model_name='jsonimport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='jsonimport',
            unique_together={('language', 'project', 'created_at')},
        ),
        migrations.RemoveField(
            model_name='jsonimport',
            name='current_datetime',
        ),
    ]
