# Generated by Django 3.2.9 on 2022-03-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation_management_tool', '0027_auto_20220304_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationkey',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='translationkey',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='translationkey',
            name='path',
        ),
    ]
