# Generated by Django 3.2.9 on 2022-03-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_management_tool', '0028_auto_20220310_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationkey',
            name='has_children',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
