# Generated by Django 3.2.9 on 2022-03-11 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translation_management_tool', '0029_translationkey_has_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fallback_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='translation_management_tool.language'),
        ),
        migrations.AddField(
            model_name='project',
            name='translatior',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
