# Generated by Django 3.2.9 on 2022-03-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation_management_tool', '0030_auto_20220311_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='translatior',
            new_name='translator',
        ),
    ]
