# Generated by Django 3.2.9 on 2022-03-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_management_tool', '0031_rename_translatior_project_translator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationkey',
            name='has_children',
        ),
        migrations.AlterField(
            model_name='translationkey',
            name='key',
            field=models.CharField(help_text="<p>For more information about the i18next value options <a href='https://www.i18next.com/misc/json-format' target='_blank'>click here</a>.</p>", max_length=255),
        ),
    ]
